#!/usr/bin/env bash
# Generate deploy/.env with cryptographically strong secrets (never printed to stdout).
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="${ROOT_DIR}/deploy/.env"
EXAMPLE="${ROOT_DIR}/deploy/.env.example"

gen_hex() {
  openssl rand -hex "${1:-32}"
}

gen_base64() {
  # 48 bytes -> 64+ base64 chars; strip chars that are awkward in .env values
  openssl rand -base64 48 | tr -d '\n/+=' | head -c 64
}

if [[ -f "${ENV_FILE}" ]]; then
  echo "deploy/.env already exists. Remove it first to regenerate secrets."
  exit 1
fi

POSTGRES_PASSWORD="$(gen_hex 32)"
JWT_ACCESS_SECRET="$(gen_base64)"
JWT_REFRESH_SECRET="$(gen_base64)"

# Defaults aligned with deploy/.env.example (non-secret values only)
POSTGRES_USER="${POSTGRES_USER:-med_warehouse}"
POSTGRES_DB="${POSTGRES_DB:-med_warehouse}"
NODE_ENV=production
API_PREFIX=api/v1
LOG_LEVEL=info
JWT_ACCESS_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=7d
THROTTLE_TTL=60
THROTTLE_LIMIT=100
THROTTLE_FORGOT_PASSWORD_LIMIT=5
SMTP_HOST="${SMTP_HOST:-smtp.yandex.ru}"
SMTP_PORT="${SMTP_PORT:-465}"
SMTP_USER="${SMTP_USER:-}"
SMTP_PASSWORD="${SMTP_PASSWORD:-}"
SMTP_FROM="${SMTP_FROM:-}"
SETTINGS_ENCRYPTION_KEY="${SETTINGS_ENCRYPTION_KEY:-$(openssl rand -hex 32)}"
VITE_API_URL="${VITE_API_URL:-/api/v1}"
VITE_APP_ENV=production
APP_URL="${APP_URL:-http://192.168.11.8}"
HTTP_PORT=80
API_PORT=3000
POSTGRES_PORT=5432

umask 077
cat > "${ENV_FILE}" <<EOF
# Medical Warehouse Management System — production deployment environment
# Generated by deploy/scripts/generate-prod-env.sh — do not commit (see .gitignore).

# PostgreSQL
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}

# Backend API
NODE_ENV=${NODE_ENV}
API_PREFIX=${API_PREFIX}
LOG_LEVEL=${LOG_LEVEL}
JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
JWT_ACCESS_EXPIRES_IN=${JWT_ACCESS_EXPIRES_IN}
JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN}
THROTTLE_TTL=${THROTTLE_TTL}
THROTTLE_LIMIT=${THROTTLE_LIMIT}
THROTTLE_FORGOT_PASSWORD_LIMIT=${THROTTLE_FORGOT_PASSWORD_LIMIT}

# Password reset emails (Yandex SMTP — set SMTP_USER and SMTP_PASSWORD before deploy)
SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_USER=${SMTP_USER}
SMTP_PASSWORD=${SMTP_PASSWORD}
SMTP_FROM=${SMTP_FROM}
SETTINGS_ENCRYPTION_KEY=${SETTINGS_ENCRYPTION_KEY}

# Frontend (Vite build-time)
VITE_API_URL=${VITE_API_URL}
VITE_APP_ENV=${VITE_APP_ENV}
GEMINI_API_KEY=
APP_URL=${APP_URL}

# Published ports (host mapping)
HTTP_PORT=${HTTP_PORT}
API_PORT=${API_PORT}
POSTGRES_PORT=${POSTGRES_PORT}
EOF
chmod 600 "${ENV_FILE}"

echo "Created ${ENV_FILE} with production secrets (values not shown)."
echo "Review APP_URL, SMTP_USER, SMTP_PASSWORD, SMTP_FROM, and GEMINI_API_KEY before deploy."
